### PR TITLE
Migrate profiles

### PR DESCRIPTION
**Pull request by AliveDevil**
ToDo:
- [x] Migrate Github Workflow
- [x] Migrate Credentials
- [ ] Verify scripts
- [x] Redirect all Download references

### CODE REVIEW

**Comment by AliveDevil** [comment]
@dkocher The AWS credentials in this repository, do these work for profiles.cyberduck.io as well?

**Comment by AliveDevil** [comment]
Using the path _static/profiles results in duplicate files for download references.
e.g. file in `_static/profiles/profile.cyberduckprofile` and referenced through ``{download}`Title</_static/profiles/profile.cyberduckprofile>` `` will be copied to `_build/dirhtml/_static` and `_build/dirhtml/_downloads/<hash>/`.

Is this something we want to avoid?

**Review by dkocher — APPROVED** [review]

**Comment by dkocher** [comment]
> Using the path _static/profiles results in duplicate files for download references. e.g. file in `_static/profiles/profile.cyberduckprofile` and referenced through `` {download}`Title</_static/profiles/profile.cyberduckprofile>` `` will be copied to `_build/dirhtml/_static` and `_build/dirhtml/_downloads/<hash>/`.
> 
> Is this something we want to avoid?

We can just reference the profiles in S3 located at `http://profiles.cyberduck.io.s3.amazonaws.com/`.

**Comment by AliveDevil** [comment]
Then having these files in _static isn't going to be something I'd like to see, because the profile files will automatically get uploaded back to the docs page.
I'll revisit the folder there, because there is no need for them to be on the docs-site if they are delivered from the profiles-site.

**Comment by AliveDevil** [comment]
Decision to locate these in [iterate-ch/profiles](https://github.com/iterate-ch/profiles).
Links still edited.

**Pull request merged**
